import React, { useState, useEffect, useRef, useMemo } from 'react';
import Navbar from './components/Navbar';
import Hero from './components/Hero';
import FeedConfigurator from './components/FeedConfigurator';
import FeedPreview from './components/FeedPreview';
import CodeGenerator from './components/CodeGenerator';
import { Button } from "./components/ui/button";
import { Code2, Zap, Layout, RefreshCw, AlertCircle } from 'lucide-react';
import { Toaster } from "./components/ui/sonner";
import { mockPosts } from './lib/mockData';

export default function App() {
  const [config, setConfig] = useState({
    username: '', // Will be filled from API data if available
    hashtag: '',
    feedType: 'fixed',
    columns: 5,
    rows: 1,
    gap: 12,
    showCaptions: true,
    refreshInterval: 300
  });
  
  const [isCodeOpen, setIsCodeOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [realPosts, setRealPosts] = useState([]);
  const [useRealData, setUseRealData] = useState(false);
  const [lastUpdated, setLastUpdated] = useState(null);
  
  const configSectionRef = useRef(null);

  const scrollToConfig = () => {
    configSectionRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  // Function to fetch the JSON generated by Python
  const fetchRealData = async () => {
    setIsLoading(true);
    try {
      // Tenta buscar o arquivo posts.json que está na raiz do site
      // O caminho relativo "./posts.json" funciona tanto local quanto no GitHub Pages
      const response = await fetch('./posts.json?t=' + new Date().getTime()); 
      
      if (!response.ok) throw new Error("Arquivo de posts não encontrado");
      
      const data = await response.json();
      
      if (Array.isArray(data) && data.length > 0) {
        // Transform data to match our internal structure
        const formattedPosts = data.map(post => ({
          id: post.id,
          imageUrl: post.media_url,
          likes: 0, // API Basic Display doesn't give likes count easily without extra permissions
          comments: 0,
          caption: post.caption || "",
          date: post.timestamp,
          permalink: post.permalink
        }));
        
        setRealPosts(formattedPosts);
        setUseRealData(true);
        
        // Auto-fill username if empty
        if (data[0].username && !config.username) {
            setConfig(prev => ({...prev, username: data[0].username}));
        }
        
        setLastUpdated(new Date());
      }
    } catch (error) {
      console.error("Could not load real data, using mocks:", error);
      setUseRealData(false);
    } finally {
      setIsLoading(false);
    }
  };

  // Initial load
  useEffect(() => {
    fetchRealData();
  }, []);

  const handleUpdatePreview = () => {
    fetchRealData();
  };

  // Filter posts based on hashtag if provided
  const filteredPosts = useMemo(() => {
    const source = useRealData ? realPosts : mockPosts;
    
    if (!config.hashtag || !useRealData) return source;
    
    const tag = config.hashtag.replace('#', '').toLowerCase();
    return source.filter(post => 
      post.caption && post.caption.toLowerCase().includes(tag)
    );
  }, [realPosts, useRealData, config.hashtag]);

  return (
    <div className="min-h-screen bg-background font-sans text-foreground selection:bg-primary/20">
      <Navbar />
      
      <main>
        <Hero scrollToConfig={scrollToConfig} />
        
        {/* Main App Section */}
        <section ref={configSectionRef} className="py-16 bg-muted/30 relative">
          <div className="container mx-auto px-4">
            <div className="flex flex-col lg:flex-row gap-8 items-start">
              
              {/* Left: Config */}
              <div className="w-full lg:w-1/3 lg:sticky lg:top-24 z-10">
                <FeedConfigurator 
                  config={config} 
                  setConfig={setConfig} 
                  onGenerate={handleUpdatePreview}
                  isLoading={isLoading}
                />
                
                <div className="mt-6 p-4 bg-blue-50 dark:bg-blue-950/30 border border-blue-100 dark:border-blue-900 rounded-lg flex flex-col gap-3">
                  <div className="flex gap-3">
                    <div className="p-2 bg-blue-100 dark:bg-blue-900 rounded-full h-fit">
                        <Zap className="w-4 h-4 text-blue-600 dark:text-blue-400" />
                    </div>
                    <div>
                        <h4 className="font-semibold text-sm text-blue-900 dark:text-blue-100">
                            {useRealData ? "Connected to Instagram" : "Demo Mode"}
                        </h4>
                        <p className="text-xs text-blue-700 dark:text-blue-300 mt-1">
                            {useRealData 
                                ? `Showing real posts. Last checked: ${lastUpdated?.toLocaleTimeString()}` 
                                : "Showing sample data. Configure your GitHub Secret to see real posts."}
                        </p>
                    </div>
                  </div>
                  {!useRealData && (
                      <div className="text-xs text-amber-600 bg-amber-50 p-2 rounded border border-amber-200 flex gap-2 items-center">
                          <AlertCircle className="w-3 h-3" />
                          <span>Waiting for IG_TOKEN in GitHub Secrets</span>
                      </div>
                  )}
                </div>
              </div>

              {/* Right: Preview */}
              <div className="w-full lg:w-2/3">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-2xl font-bold tracking-tight">Live Preview</h2>
                  <div className="flex gap-2">
                    <Button 
                        variant="outline" 
                        size="sm" 
                        className="hidden sm:flex"
                        onClick={handleUpdatePreview}
                        disabled={isLoading}
                    >
                        <RefreshCw className={`w-4 h-4 mr-2 ${isLoading ? 'animate-spin' : ''}`} />
                        Refresh Preview
                    </Button>
                    <Button onClick={() => setIsCodeOpen(true)} className="bg-gradient-primary shadow-lg shadow-primary/20">
                        <Code2 className="w-4 h-4 mr-2" />
                        Get Embed Code
                    </Button>
                  </div>
                </div>
                
                <FeedPreview 
                    config={config} 
                    isLoading={isLoading} 
                    posts={filteredPosts} // Pass filtered posts directly
                />
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="py-24 bg-white dark:bg-card">
          <div className="container mx-auto px-4">
            <div className="text-center max-w-2xl mx-auto mb-16">
              <h2 className="text-3xl font-bold mb-4">Why use InstaWix?</h2>
              <p className="text-muted-foreground">Everything you need to showcase your social proof effectively.</p>
            </div>

            <div className="grid md:grid-cols-3 gap-8">
              {[
                {
                  icon: <Layout className="w-6 h-6 text-primary" />,
                  title: "Smart Layouts",
                  desc: "Choose between a fixed 5-post strip or a fully custom grid up to 10x10."
                },
                {
                  icon: <RefreshCw className="w-6 h-6 text-primary" />,
                  title: "Auto-Updates",
                  desc: "Feeds automatically refresh in the background to show your latest content."
                },
                {
                  icon: <Zap className="w-6 h-6 text-primary" />,
                  title: "GitHub Actions Powered",
                  desc: "Uses serverless automation to fetch your posts every 15 minutes for free."
                }
              ].map((feature, i) => (
                <div key={i} className="p-6 rounded-2xl bg-muted/30 border hover:border-primary/50 transition-colors">
                  <div className="w-12 h-12 rounded-xl bg-white dark:bg-background shadow-sm flex items-center justify-center mb-4">
                    {feature.icon}
                  </div>
                  <h3 className="text-xl font-semibold mb-2">{feature.title}</h3>
                  <p className="text-muted-foreground">{feature.desc}</p>
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="py-12 border-t bg-muted/20">
        <div className="container mx-auto px-4 text-center text-muted-foreground text-sm">
          <p>&copy; 2024 InstaWix Feed Generator. Built for creators.</p>
        </div>
      </footer>

      <CodeGenerator 
        open={isCodeOpen} 
        onOpenChange={setIsCodeOpen} 
        config={config} 
      />
      <Toaster />
    </div>
  );
}
